### ISSUE TITLE
Website crashes when pinch zooming on iOS 15.6

### ISSUE THREAD

**Issue by Malien** [fasterthanlime/feedback#99] opened 2022-08-20 09:12 UTC
It’s not an article inaccuracy, but more likely an iOS safari bug (of course it’s iOS safari, what other browser would have this much problems? _Apart from old IE_)

**Where's the problem at?**
Pretty much every article page (not the home one though)

**No, seriously, where is it?**
When zooming in and out, sometimes page crashes. It does it pretty consistently though, and I couldn’t reproduce this crashing behaviour on other sites. 

https://user-images.githubusercontent.com/7205038/185738109-01f74fdb-3627-4a6c-b9bf-b3da0b471a14.MOV

I mean, the pictures of code are sometimes small on small phone screens, so I reach to pinch zooming on articles somewhat regularly.

**Describe the issue and a fix if you know it**
I don’t know what exactly on the page causes it, whether it’s local to my device (I do not possess more iOS 15.6 devices), and whether or not it can be circumvented. It’s probably a Safari bug, and I understand if you pay no attention to this issue. Investigating this further is probably not worth it. Just want it to be noted somewhere.

**Comment by FredrikAugust** [comment] 2023-01-02 14:36
Still an issue, sadly! Experienced on:

`iOS 16.0.3 (20A392)`

**Comment by fasterthanlime** [comment] 2023-03-11 22:22
Closing as duplicate of #37 (but not solved..)

**Closed by fasterthanlime** 2023-03-11 22:22 UTC
Labels: blocked
